[build]
    publish = "public"
    command = """
    npm run build:css
    zola build
    """

[build.environment]
    ZOLA_VERSION = "0.13.0"
    NODE_VERSION = "0.15"

[context.deploy-preview]
    # The magic for deploying previews of branches
    # We need to override the base url with whatever url Netlify assigns to our
    # preview site.  We do this using the Netlify environment variable
    # `$DEPLOY_PRIME_URL`.
    command = """
    npm run build:css
    zola build --drafts --base-url $DEPLOY_PRIME_URL
    """
